[19기 함경재] Add: CompanyMenuView 구현
wecode-bootcamp-korea/19-2nd-her-house-backend pull request #3
Opened 2021-04-29 03:00 UTC by hiyee-gj

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- companies/views.py View 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- CompanyMenuView 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-04-29 04:52 UTC, redsaumon commented on companies/views.py
> +            for company in Company.objects.all()]
Company와 함께 가져와보시는 건 어떨까요?

2021-04-29 05:00 UTC, hiyee-gj commented on companies/views.py
> +            for company in Company.objects.all()]
아하 아주 좋은 방법이네요!!

2021-04-29 05:44 UTC, redsaumon commented on companies/views.py
> +            for company in Company.objects.all()]
prefetch_related에 대해 공부하시고 적용해주세요!

2021-04-29 05:53 UTC, hiyee-gj commented on companies/views.py
> +            for company in Company.objects.all()]
오호...강해져서 오겠습니다

2021-04-30 10:20 UTC, redsaumon commented
경재님 테스트 성공한 화면도 캡쳐해서 올려주세요!

2021-04-30 10:33 UTC, hiyee-gj commented
> 경재님 테스트 성공한 화면도 캡쳐해서 올려주세요!

넵넵 올렸습니다!!

2021-05-01 05:02 UTC, redsaumon requested changes

2021-05-01 05:02 UTC, redsaumon commented on companies/tests.py
> +        location = '서울시 강남구 어디쯤'
쿼리스트링으로 보내주는데 이제 이 변수는 필요 없겠죠?

2021-05-01 08:52 UTC, hiyee-gj commented on companies/tests.py
> +        location = '서울시 강남구 어디쯤'
아 넵넵!!

2021-05-01 09:27 UTC, merged

2021-05-01 09:28 UTC, redsaumon commented
수고하셨습니다~

2021-05-01 09:28 UTC, hiyee-gj commented
> 수고하셨습니다~

아유 연우님이 더 고생하셨습니다!!